"""followers relations

Revision ID: 16724e7545b9
Revises: 249011012d3b
Create Date: 2019-06-19 15:41:45.402389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16724e7545b9'
down_revision = '249011012d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
