"""added user info for profile

Revision ID: 249011012d3b
Revises: 5eaf95c7f351
Create Date: 2019-06-18 20:47:01.201821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249011012d3b'
down_revision = '5eaf95c7f351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
